Comic-Api/Comic-Api/Controllers/AlignmentController.cs
using Comic_Api.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;

namespace Comic_Api.Controllers
{
    public class AlignmentController : Controller
    {
        private List<Hero> heroes;
        private AlignmentListModel viewModel = new AlignmentListModel();

        public AlignmentController()
        {
            string jsonFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "heroes.json");
            string json = System.IO.File.ReadAllText(jsonFilePath);
            heroes = JsonSerializer.Deserialize<List<Hero>>(json);

            viewModel.Publishers = heroes.Select(h => h.biography.publisher).Distinct().ToList();
            Fill();
        }

        public IActionResult Index()
        {
            ViewBag.GoodColor = "blue";
            ViewBag.NeutralColor = "gray";
            ViewBag.BadColor = "red";

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult FilterHeroes(string publisher)
        {
            if (string.IsNullOrEmpty(publisher))
            {
                Fill();
            }
            else
            {
                viewModel.GoodHeroList = heroes.Where(h => h.biography.publisher == publisher && h.biography.alignment == "good").ToList();
                viewModel.BadHeroList = heroes.Where(h => h.biography.publisher == publisher && h.biography.alignment == "bad").ToList();
                viewModel.NeutralHeroList = heroes.Where(h => h.biography.publisher == publisher && h.biography.alignment == "-").ToList();
            }

            ViewBag.GoodColor = "blue";
            ViewBag.NeutralColor = "gray";
            ViewBag.BadColor = "red";

            return View("Index", viewModel);
        }

        private void Fill()
        {
            viewModel.GoodHeroList = heroes.Where(h => h.biography.alignment == "good").ToList();
            viewModel.BadHeroList = heroes.Where(h => h.biography.alignment == "bad").ToList();
            viewModel.NeutralHeroList = heroes.Where(h => h.biography.alignment == "-").ToList();
        }
    }
}

Comic-Api/Comic-Api/Controllers/ComicVineController.cs
using Comic_Api.Models;
using Microsoft.AspNetCore.Mvc;

namespace Comic_Api.Ui.Mvc.Controllers
{
	public class ComicVineController : Controller
	{
		private ComicVineApi _comicVineApi;

		public IActionResult Index()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Index(string heroName)
		{
			if (string.IsNullOrEmpty(heroName))
			{
				// Handle empty input
				return RedirectToAction(nameof(Index));
			}

			var comicVineApi = new ComicVineApi(); // Create an instance of ComicVineApi
			var superheroComics = await comicVineApi.SearchHero(heroName);
            if (superheroComics._responseVolume.Length == 0)
            {
	            superheroComics._response.error = "NotFound";
            }

			// Pass the retrieved data to the view
			return View(superheroComics);
		}
		[HttpGet]
		public IActionResult Movie()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Movie(string MovieName)
		{
			if (string.IsNullOrEmpty(MovieName))
			{
				// Handle empty input
				return RedirectToAction(nameof(Movie));
			}

			var comicVineApi = new ComicVineApi(); // Create an instance of ComicVineApi
			var SuperheroMovies = await comicVineApi.GetMovie(MovieName);


			// Pass the retrieved data to the view
			return View(SuperheroMovies);
		}
	}
}

Comic-Api/Comic-Api/Controllers/CompareController.cs
using Comic_Api.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Comic_Api.Controllers
{
	public class CompareController : Controller
	{
		private List<Hero> heroes;
		private static List<Hero> comparedHeroes = new List<Hero>();
		private HeroListsViewModel viewModel = new HeroListsViewModel();

		public CompareController()
		{
			string jsonFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "heroes.json");
			string json = System.IO.File.ReadAllText(jsonFilePath);
			heroes = JsonSerializer.Deserialize<List<Hero>>(json);
		}

		[HttpGet]
		public IActionResult Index()
		{
			fill();
			return View(viewModel);
		}

		[HttpPost]
		public IActionResult Index(int id)
		{
			if (comparedHeroes.Count == 2)
			{
				ViewBag.ErrorMessage = "You can only compare up to two heroes. Clear the heroes or compare them";
				fill();
				return View(viewModel);
			}

			if (comparedHeroes.Any(h => h.id == id))
			{
				ViewBag.ErrorMessage = "You can't compare the same hero";
				fill();
				return View(viewModel);
			}

			var result = heroes.FirstOrDefault(h => h.id == id);
			if (result != null)
			{
				comparedHeroes.Add(result);
				fill();
			}

			return View(viewModel);
		}

		[HttpGet]
		public IActionResult Compare()
		{
			return View(comparedHeroes);
		}

		[HttpPost]
		public IActionResult Search(string query)
		{
			if (string.IsNullOrWhiteSpace(query))
			{
				var originalHeroesHtml = GenerateHeroesHtml(heroes);
				return Content(originalHeroesHtml, "text/html");
			}

			var results = heroes.Where(h => h.name.ToLower().Contains(query.ToLower())).ToList();
			var searchResultsHtml = GenerateHeroesHtml(results);

			return Content(searchResultsHtml, "text/html");
		}


		public IActionResult Clear()
		{
			comparedHeroes.Clear();
			fill();
			return View("Index", viewModel);
		}

		private void fill()
		{
			viewModel.HeroesList1 = heroes;
			viewModel.HeroesList2 = comparedHeroes;
		}


		private string GenerateHeroesHtml(List<Hero> heroesList)
		{
			StringBuilder htmlBuilder = new StringBuilder();
			foreach (var hero in heroesList)
			{
				htmlBuilder.Append("<div class=\"character\">");
				htmlBuilder.Append("<form method=\"post\" action=\"/Compare/Index\" id=\"compareForm\">");
				htmlBuilder.Append($"<input type=\"hidden\" id=\"heroId\" name=\"id\" value=\"{hero.id}\">");
				htmlBuilder.Append("<button type=\"button\" class=\"characterButton\" onclick=\"selectCharacter(" + hero.id + ")\">");
				htmlBuilder.Append($"<h2>{char.ToUpper(hero.name[0]) + hero.name.Substring(1)}</h2>");
				htmlBuilder.Append($"<img src=\"{hero.images.xs}\" alt=\"{hero.name}\" class=\"img-fluid\">");
				htmlBuilder.Append("</button>");
				htmlBuilder.Append("</form>");
				htmlBuilder.Append("</div>");
			}
			return htmlBuilder.ToString();
		}
	}
}

Comic-Api/Comic-Api/Controllers/HeroController.cs
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Comic_Api.Models;
using Comic_Api.Models.DB;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;

namespace Comic_Api.Controllers
{
	public class HeroController : Controller
	{
		private List<Hero> heroes;
		private static String Methode = "";

		public HeroController()
		{
			string jsonFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "heroes.json");
			string json = System.IO.File.ReadAllText(jsonFilePath);
			heroes = JsonSerializer.Deserialize<List<Hero>>(json);
		}


		[HttpGet]
		public ActionResult Search(string query)
		{
			List<Hero> results = new List<Hero>();
			Methode = "Search";

			if (string.IsNullOrEmpty(query))
			{
				ViewBag.ErrorMessage = "Search a hero please.";
				return View(results);
			}

			if (!string.IsNullOrEmpty(query))
			{
				results = heroes.Where(h => h.name.Contains(query)).ToList();
			}

			return View(results);
		}

		[HttpGet]
		public ActionResult SearchEmpty()
		{
			Methode = "searchEmpty";
			if (string.IsNullOrEmpty(Request.Cookies["UserID"]))
			{
				if (TempData["Error"] != null)
				{
					ViewBag.ErrorMessage = TempData["Error"];
				}
			}
			else
			{
				String UserIDS = Request.Cookies["UserID"];
				int UserID = Convert.ToInt32(UserIDS);

				FavoriteSuperheroDB DB = new FavoriteSuperheroDB();
				var listFavvanUser = DB.GetFavoriteSuperheroesByUserID(UserID);
				ViewBag.ListFavs = listFavvanUser;
			}

			string query = TempData["SearchQuery"] as string;

			List<Hero> results = new List<Hero>();

			if (string.IsNullOrEmpty(query))
			{
				return RedirectToAction("Search");
			}

			query = query.ToLower();
			query = query.TrimStart();
			query = query.TrimEnd();

			var exactMatches = heroes.Where(h => h.name.ToLower() == query).ToList();
			results.AddRange(exactMatches);

			if (exactMatches.Count == 0)
			{
				var KoppeltekenQuery = query.Replace(" ", "-");
				var nietKoppeltekenQuery = query.Replace("-", " ");

				var KoppeltekenMatch = heroes.Where(h => h.name.ToLower() == KoppeltekenQuery).ToList();
				results.AddRange(KoppeltekenMatch);

				if (KoppeltekenMatch.Count == 0)
				{
					var nietKoppeltekenMatch = heroes.Where(h => h.name.ToLower() == nietKoppeltekenQuery).ToList();
					results.AddRange(nietKoppeltekenMatch);

					if (nietKoppeltekenMatch.Count == 0)
					{
						results.AddRange(heroes.Where(h => h.name.ToLower().Contains(query)).ToList());
					}
				}
			}

			if (results.Count == 0)
			{
				ViewBag.ErrorMessage = "No results found.";
			}

			return View("Search", results);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult SearchPost(string query)
		{
			Methode = "SearchPost";
			if (string.IsNullOrEmpty(Request.Cookies["UserID"]))
			{

			}
			else
			{
				String UserIDS = Request.Cookies["UserID"];
				int UserID = Convert.ToInt32(UserIDS);

				FavoriteSuperheroDB DB = new FavoriteSuperheroDB();
				var listFavvanUser = DB.GetFavoriteSuperheroesByUserID(UserID);
				ViewBag.ListFavs = listFavvanUser;
			}

			List<Hero> results = new List<Hero>();

			if (string.IsNullOrEmpty(query))
			{
				return RedirectToAction("Search");
			}

			query = query.ToLower();
			query = query.TrimStart();
			query = query.TrimEnd();

			var exactMatches = heroes.Where(h => h.name.ToLower() == query).ToList();
			results.AddRange(exactMatches);

			if (exactMatches.Count == 0)
			{
				var KoppeltekenQuery = query.Replace(" ", "-");
				var nietKoppeltekenQuery = query.Replace("-", " ");

				var KoppeltekenMatch = heroes.Where(h => h.name.ToLower() == KoppeltekenQuery).ToList();
				results.AddRange(KoppeltekenMatch);

				if (KoppeltekenMatch.Count == 0)
				{
					var nietKoppeltekenMatch = heroes.Where(h => h.name.ToLower() == nietKoppeltekenQuery).ToList();
					results.AddRange(nietKoppeltekenMatch);

					if (nietKoppeltekenMatch.Count == 0)
					{
						results.AddRange(heroes.Where(h => h.name.ToLower().Contains(query)).ToList());
					}
				}
			}

			if (results.Count == 0)
			{
				ViewBag.ErrorMessage = "No results found.";
			}

			return View("Search", results);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult SearchPost2(string query, int ID, bool Bool)
		{
			
			TempData["SearchQuery"] = query;
			if (string.IsNullOrEmpty(Request.Cookies["UserID"]))
			{
				ViewBag.ErrorMessage = "You must be logged in.";
				TempData["Error"] = "You must be logged in.";
				return RedirectToAction("SearchEmpty");
			}
			else
			{
				String UserIDS = Request.Cookies["UserID"];
				int UserID = Convert.ToInt32(UserIDS);

				FavoriteSuperheroDB DB = new FavoriteSuperheroDB();
				var listFavvanUser = DB.GetFavoriteSuperheroesByUserID(UserID);
				ViewBag.ListFavs = listFavvanUser;


				if (!Bool)
				{
					DB.AddFavoriteSuperhero(UserID, ID);
					if (Methode.Equals("SearchFavoriteHeroesOnID"))
					{
						TempData["SearchQuery"] = null;
					//	return RedirectToAction("SearchFavoriteHeroesOnID");
					}
				}
				else
				{
					DB.RemoveFavoriteSuperhero(UserID, ID);
					//ViewBag.ErrorMessage = "Je zal deze unfavoriten";
					if (Methode.Equals("SearchFavoriteHeroesOnID"))
					{
						TempData["SearchQuery"] = null;
						//return RedirectToAction("SearchFavoriteHeroesOnID");
					}
				}

				//return RedirectToAction("SearchEmpty");
				if (Methode != "")
				{
					if (Methode.Equals("SearchPost"))
					{
						return RedirectToAction("SearchEmpty");
					}
					else
					{
						return RedirectToAction(Methode);
					}
				}
				else
				{
					return RedirectToAction("Search");
				}
			}
		}

		public ActionResult SearchFavoriteHeroesOnID()
		{
			Methode = "SearchFavoriteHeroesOnID";
			if (string.IsNullOrEmpty(Request.Cookies["UserID"]))
			{
				ViewBag.ErrorMessage = "You need to be logged in.";
				return View("Search");
			}
			else
			{
				String UserIDS = Request.Cookies["UserID"];
				int UserID = Convert.ToInt32(UserIDS);

				FavoriteSuperheroDB DB = new FavoriteSuperheroDB();
				var listFavvanUser = DB.GetFavoriteSuperheroesByUserID(UserID);
				ViewBag.ListFavs = listFavvanUser;


				List<Hero> results = new List<Hero>();


				foreach (Hero h in heroes)
				{
					foreach (FavoriteSuperhero s in listFavvanUser)
					{
						if (h.id == s.SuperheroID)
						{
							results.Add(h);
						}
					}
					
				}

			
				return View("Search",results);
			}

			


			
		}
	}
}

Comic-Api/Comic-Api/Views/Shared/_Layout.cshtml
@using Comic_Api.Models.DB
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comic_Api</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Comic_Api.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comic_Api</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	                <ul class="navbar-nav flex-grow-1">
		                <li class="nav-item">
			                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link" asp-area="" asp-controller="Hero" asp-action="Search">Search</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link" asp-area="" asp-controller="Compare" asp-action="Index">Compare</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link" asp-area="" asp-controller="ComicVine" asp-action="Movie">Movies</a>
		                </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Alignment" asp-action="Index">Alignment</a>
                        </li>
	                </ul>
                    <ul class="navbar-nav">
	                    @{
		                    var userId = Context.Request.Cookies["UserID"];
		                    var loginAction = string.IsNullOrEmpty(userId) ? "Index" : "Logout";
		                    var loginText = string.IsNullOrEmpty(userId) ? "Login" : "Logout";

		                    
		                    var userName = string.Empty;
		                    if (!string.IsNullOrEmpty(userId))
		                    {
			                    UserDB userDB = new UserDB();
			                    var user = userDB.GetUserByID(int.Parse(userId));
                                userName = "User: " + user.FirstName + " " + user.LastName;
		                    }
	                    }
                        <li class="nav-item">
                            <p class="nav-link">@userName</p>
                        </li>
	                    <li class="nav-item">
	                        <a class="nav-link" asp-area="" asp-controller="Login" asp-action="@loginAction"> @loginText</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>